### ISSUE TITLE
Can't login using default credentials

### ISSUE THREAD

**Issue by GreenEminence** [cgwire/cgwire#7]
Hello,
I tried to deploy your docker image on a local machine (macOS). It's throwing "Login failed" error when I'm trying to log into Kitsu using default credentials. 
Chrome console outputs "Method Not Allowed The method is not allowed for the requested URL." message on /auth/login API path (HTTP 400 error is returned).

**Comment by frankrousseau** [comment]
Hi @GreenEminence, 
Thank you for reporting. Someone else just reported the bug via email. We are on it. We'll notify you as soon as it is fixed.

**Comment by frankrousseau** [comment]
Hello @GreenEminence,
  
The problem should be fixed. Could you try again?

I added automatic tests after each build to minimize the risk that it happens again.

**Comment by GreenEminence** [comment]
Hello @frankrousseau,

Sorry for delayed response. After updating the image, I'm still having same issue. Now it's actually: 
`Failed to load resource: the server responded with a status of 400 (BAD REQUEST)`.

During the build process, it also fails to build wheel for supervisor.

**Comment by frankrousseau** [comment]
Yes if you build it locally, you need the latest version of `pip`, `wheel` and `setuptools`. But you can use the image directly from the Dockerhub:

```
docker run -ti --rm -p 80:80 --name cgwire cgwire/cgwire
```

**Comment by GreenEminence** [comment]
Hello @frankrousseau,
Recently I tried building a docker image locally and it finally works. Still no luck when trying to pull the image from Dockerhub.

Thanks for your help!
